{% extends 'layout/layout.swig' %}
{% block title %}首页{% endblock %}
{% block description %}{% endblock %}
{% block keywords %}{% endblock %}
{% block stylesheets %}
{% endblock %}
{% block scripts %}
<script src="/assets/js/_lib.js" type="text/javascript"></script>
<script src="/assets/js/pub.js" type="text/javascript"></script>
<script src="/assets/js/page-main.js" type="text/javascript"></script>
{% endblock %}
{% block content %}
<module-module1></module-module1>
{% endblock %}
